### ISSUE TITLE
Track pack openings

### ISSUE THREAD

**Issue by losttime** [gregstewart/hearthstone-tracker#273]
Would you be interested in including a mechanism to track pack openings?

I'm thinking of something that would track how close you are to hitting your pity timer limits for Legendaries, Epics, and golden cards.

I'd be available to help or lead out on coding this up if it's something you're willing to incorporate.

**Comment by gregstewart** [comment]
@losttime I hadn't considered that feature, but I think it's certainly a good idea and I am more than happy for you to have a go at implementing this. 

I hadn't looked into whether this appeared in the log files, have you looked into what is logged to implement this?

**Comment by losttime** [comment]
Thanks for getting back to me.

The pack opening logs aren't found in the log file currently watched by farseer, but there are other log files that can be watched and parsed. I believe the info can be found in one of those.

I'll likely attempt to implement the log watching in farseer, then have it emit new events so the stats can be tracked here in hearthstone-tracker.

**Comment by losttime** [comment]
I may have gotten ahead of myself. It looks like Hearthstone used to log info about pack openings, but stopped a little over a year ago - https://github.com/jleclanche/fireplace/issues/236

I'll see what other options are available, but I don't have high hopes. This is probably why [Pity Tracker](http://pitytracker.com/) has you enter your pack results manually.

**Comment by gregstewart** [comment]
That's a shame, I will go ahead and close this issue then. Thanks for looking into it!

**Comment by losttime** [comment]
I don't know when this started, but I'm seeing `NotifyOfCardGained` in my `Achievements.log` file. It looks like Blizzard is logging pack openings again (or I'm looking at a very old log).
